### ISSUE TITLE
[BUG] - 403 Minget error

### ISSUE THREAD

**Issue by AleixFerre** [CatalaHD/CataBot#158]
**Describe the bug**
Sometimes the bot decides to break. It seems a library bug (see the link [here](https://github.com/fent/node-ytdl-core/issues/932))
It appears like a 403 error.

**To Reproduce**
It seems random...

**Expected behavior**
Just reproduce the song lmao

**Screenshots & Logs**
```
--- Nova comanda ---
  Contingut: !playnow https://youtu.be/DHnl4hPbizw?list=RDAn9jzkdUMdg
MinigetError: input stream: Status code: 403
    at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:210:27)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  statusCode: 403
}
```
![image](https://user-images.githubusercontent.com/12767963/136671602-8991ac9e-a4a5-4714-b390-eb300ee80692.png)

**Possible Solutions**
Just check for errors in this stage and loop while there's an error until there's none.

**Comment by Arniox** [comment]
I get the same error on random videos

**Comment by AleixFerre** [comment]
@Arniox Look at what I came up with 
https://github.com/AleixFerre/CataBot/blob/bee20ba7b1a5119ca073a6d8eb998929447742e7/lib/musicModule.js#L143

First i have a local `tries` variable that start at 0.

And just try in a loop (I have limited it max 5 times).

Remember to restart the counter `on('start')` in order not to propagate the number of tries to future songs in the recursive call stack.

Catch the error in `on.('error')` like so (or change it to work in your code rather):

```js
.on('error', (err) => {
        if (tries < 5) {
          setTimeout(() => {
            message.channel.send(`**⚠ There's an error trying to play the song, retrying... (try ${tries + 1}/5)**`);
            video_player(message, song, voice_channel_name, seekTime, tries + 1); // Recursive call to this same function but with one more try
          }, 1000); // Wait 1s just not to spam the API
        } else {
          // 5 tries and the error persists.
          // Remove all the guild song queue
          // Get out of the voice channel
          // Send an special error message to notify the user that something broke
          // If possible inform yourself (or the main dev). Make the bot send you a message logging/informing that something big happened
        }
```

Like here https://github.com/AleixFerre/CataBot/blob/bee20ba7b1a5119ca073a6d8eb998929447742e7/lib/musicModule.js#L174

---------------

This is a temporary solution of course, but it seems to work just fine. When the error happens it deals with it completely fine. And this code will work just fine if there's no error.
