### ISSUE TITLE
[BUG] - Con el comando !money

### ISSUE THREAD

**Issue by JavierLopezBlancoH** [CatalaHD/CataBot#31]
Al poner el comando !money me sale dos veces el mensaje del dinero que tengo, te adjunto imagen para que lo comprubes
![image](https://user-images.githubusercontent.com/49500332/80282459-f43c2e80-8711-11ea-9f3b-6189f4943d17.png)
Espero que lo arregles pronto, no se si es bug.
Gran trabajo con el bot sigue asi.

**Comment by CatalaHD** [comment]
Estaba corriendo el bot en distintas maquinas a la vez, no es un bug. Arreglado! :D

**Comment by CatalaHD** [comment]
Por eso te salen distintas cantidades de dinero
